[package]
name = "event-subscriber"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.90", features = ["full"] }
ctor = "0.2.9"
bincode = "1.3.3"

[lib]
proc-macro = true
